AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  expense-tracker-backend
  
  Serverless backend for Expense Tracker with OCR using AWS Textract.

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        TABLE_NAME: !Ref ExpenseTable
        UPLOAD_BUCKET: !Ref ReceiptBucket
        SNS_TOPIC_ARN: !Ref MonthlySummaryTopic

Resources:
  # -------------------------------------------------------------------------
  # S3 Bucket for Receipts
  # -------------------------------------------------------------------------
  ReceiptBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'expense-tracker-receipts-${AWS::AccountId}-${AWS::Region}'
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, HEAD]
            AllowedOrigins: ['*'] # Restrict this in production
            MaxAge: 3000

  # -------------------------------------------------------------------------
  # DynamoDB Table
  # -------------------------------------------------------------------------
  ExpenseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: expenseId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: expenseId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # -------------------------------------------------------------------------
  # SNS Topic
  # -------------------------------------------------------------------------
  MonthlySummaryTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: monthly-expense-summary

  # -------------------------------------------------------------------------
  # API Gateway
  # -------------------------------------------------------------------------
  ExpenseApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # -------------------------------------------------------------------------
  # Lambda Functions
  # -------------------------------------------------------------------------
  
  # 1. Get Upload URL
  GetUploadUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: src/handlers/getUploadUrl.handler
      Policies:
        - S3WritePolicy:
            BucketName: !Ref ReceiptBucket
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ExpenseApi
            Path: /upload-url
            Method: post

  # 2. Process Receipt (S3 Trigger)
  ProcessReceiptFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: src/handlers/processReceipt.handler
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ReceiptBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ExpenseTable
        - Statement:
            - Effect: Allow
              Action: textract:AnalyzeExpense
              Resource: "*"
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref ReceiptBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: receipts/

  # 3. Get Expenses
  GetExpensesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: src/handlers/getExpenses.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ExpenseTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ExpenseApi
            Path: /expenses
            Method: get

  # 4. Get Monthly Summary (API)
  GetMonthlySummaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: src/handlers/getMonthlySummary.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ExpenseTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ExpenseApi
            Path: /summary
            Method: get

  # 5. Monthly Summary Trigger (Scheduled)
  MonthlySummaryTriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: src/handlers/monthlySummaryTrigger.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ExpenseTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt MonthlySummaryTopic.TopicName
      Events:
        MonthlySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 12 1 * ? *) # Run at 12:00 PM UTC on the 1st of every month

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ExpenseApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ReceiptBucketName:
    Description: "S3 Bucket for storing receipts"
    Value: !Ref ReceiptBucket
  ExpenseTableName:
    Description: "DynamoDB Table for expenses"
    Value: !Ref ExpenseTable
